spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: enrolment-service
          uri: lb://enrolment-service
          predicates:
            - Path=/enrolments/**
        - id: enrolment-service-post
          uri: lb://enrolment-service
          predicates:
            - Path=/enrolments/**
            - Method=POST,PUT
          filters:
            - name: RequestSize
              args:
                maxSize: 100 KB
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**

