spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: enrolment-service
          uri: lb://enrolment-service
          predicates:
            - Path=/enrolments/**
          filters:
            - name: RequestSize
              args:
                maxSize: 700 KB
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          filters:
            - name: RequestSize
              args:
                maxSize: 100 KB
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/npbvs
