spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: enrolment-service
          uri: lb://enrolment-service
          predicates:
            - Path=/enrolments
            - Method=POST
          filters:
            - name: RequestSize
              args:
                maxSize: 700 KB
            - name: AuthenticationFilter

        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search
            - Method=POST
          filters:
            - name: RequestSize
              args:
                maxSize: 100 KB
            - name: AuthenticationFilter

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/users/**
            - Method=POST,PUT
          filters:
            - name: AuthenticationFilter
  main:
    allow-bean-definition-overriding: true
