openapi: 3.0.0
info:
  version: 1.0.0
  title: Enrolment Service API
  description: This service handled client biometrics fingerprint enrolment
paths:
  /enrolments:
    get:
      description: Returns all enrolled clients
      tags: [ "Enrolments" ]
      operationId: "get"
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ClientDTOList"

    post:
      description: The endpoint registers a new client if the submitted fingerprints does not have a match from previously submitted fingerprints.
      tags: [ "Enrolments" ]
      operationId: "enroll"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/EnrolmentDTO"
      responses:
        "201":
          description: "Created"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ClientDTO"

        400:
          description: Bad request


  /enrolments/{id}:
    get:
      description: Returns a subject by id
      tags: [ "Enrolments" ]
      operationId: "getById"
      parameters:
        - name: id
          in: path
          required: true
          description: The subject id.
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ClientDTO"
        "400":
          description: Specified subject ID is not a valid uuid
        "404":
          description: Post not found

    put:
      description: Update subject's basic information
      tags: [ "Enrolments" ]
      operationId: "update"
      parameters:
        - name: id
          in: path
          required: true
          description: The subject id
          schema:
            type: string
      responses:
        "204":
          description: Subject updated successfully
        "400":
          description: Specified subject ID is not a valid uuid

    delete:
      description: Delete enrolled subject
      tags: [ "Enrolments" ]
      operationId: "delete"
      parameters:
        - name: id
          in: path
          required: true
          description: The subject id
          schema:
            type: string
      responses:
        "204":
          description: Subject updated successfully
        "400":
          description: Specified subject ID is not a valid uuid

components:
  schemas:
    ClientDTOList:
      type: array
      items:
        $ref: "#/components/schemas/ClientDTO"

    AuxiliaryId:
      type: object
      required:
        - type
        - value
        - sourceSystemId
      properties:
        type:
          type: string
        value:
          type: string
        sourceSystemId:
          type: string

    ClientDTO:
      type: object
      required:
        - firstName
        - lastName
        - sex
        - dateOfBirth
        - newClient
      properties:
        id:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        sex:
          type: string
        dateOfBirth:
          type: string
        auxiliaryIds:
          type: array
          items:
            $ref: "#/components/schemas/AuxiliaryId"
        newClient:
          type: boolean

    EnrolmentDTO:
      type: object
      required:
        - firstName
        - middleName
        - lastName
        - sex
        - clientIdName
        - clientIdValue
      properties:
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        sex:
          type: string
        clientIdName:
          type: string
        clientIdValue:
          type: string
        rightThumb:
          type: object
        rightIndex:
          type: object
        rightMiddle:
          type: object
        rightRing:
          type: object
        rightPinky:
          type: object
        leftThumb:
          type: object
        leftIndex:
          type: object
        leftMiddle:
          type: object
        leftRing:
          type: object
        leftPinky:
          type: object

