openapi: 3.0.0
info:
  version: 1.0.0
  title: Enrolment Service API
  description: This service handled client biometrics fingerprint enrolment
paths:
  /enrolments:
    get:
      description: Returns all enrolled clients
      tags: [ "Enrolments" ]
      operationId: "getEnrolments"
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/PostsList"

  /posts/{id}:
    get:
      description: Returns a post by id
      tags: [ "Posts" ]
      operationId: "getPost"
      parameters:
        - name: id
          in: path
          required: true
          description: The user id.
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          description: Post not found

components:
  schemas:
    SubjectList:
      type: array
      items:
        $ref: "#/components/schemas/Post"
    Subject:
      type: object
      required:
        - firstName
        - lastName
        - sex
      properties:
        firstName:
          type: string
        lastName:
          type: string
        sex:

    PostsList:
      "type": "array"
      "items":
        $ref: "#/components/schemas/Post"
    Post:
      "type": "object"
      "required":
        - "id"
        - "userId"
        - "title"
      "properties":
        id:
          type: "integer"
        userId:
          type: "integer"
        title:
          type: "string"
        completed:
          type: "boolean"