server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  codec:
    max-in-memory-size: 3000KB
  webflux:
    problemdetails:
      enabled: true
